#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unalias rm
unalias gcc

# Neovim
alias vim=nvim

# Kubernetes
alias kc=kubectl

## Why would I want shared session history?
unsetopt share_history

# added by travis gem
[ -f /Users/igaitan/.travis/travis.sh ] && source /Users/igaitan/.travis/travis.sh

## AWS CLI completions
source /usr/local/share/zsh/site-functions/_aws

## Virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

# The next line updates PATH for the Google Cloud SDK.
source '/Users/igaitan/sdk/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/igaitan/sdk/google-cloud-sdk/completion.zsh.inc'

